// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzgcrxrsbzntihkjamsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6Z2NyeHJzYnpudGloa2phbXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NjA4ODIsImV4cCI6MjA2MDMzNjg4Mn0.d7fqJ8c0sKb1mwlr4jtdL2SCN8BAhF8RaKhOaFCZAZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);